### PR TITLE
get schools data

### PR DESCRIPTION
**Pull request by Prometheus0102**

### CODE REVIEW

**Review by dev-kasibhatla — APPROVED** [review]

**Comment by msvamp** [comment]
This is bugged AF
@Prometheus0102 check your JS

Bugged AF select tag

**Comment by msvamp** [comment]
Why is @dev-kasibhatla approving blindly and not even mentioning that he didn't check?

**Comment by Prometheus0102** [comment]
bcc asa kasa

**Comment by Prometheus0102** [comment]
> This is bugged AF

itka pan vait nahi ahe 😑

**Comment by Prometheus0102** [comment]
pushed correct code on server

**Comment by msvamp** [comment]
Change in your branch, push in next commit

**Pull request merged**
